name: Mod Support Request
description: Request support for a specific mod
title: '[Mod Support Request] EXAMPLE MOD'
labels: ['🧩 mod-support']
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this mod support request, make sure your mod hasn’t already been requested.

        ⚠️ If requesting support for multiple mods, please submit **separate issues** for each one.

  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: The name of the mod you’re requesting support for.
      placeholder: 'Example Mod'
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Link to the mod page
      description: Provide a direct URL to the mod’s homepage.
      placeholder: 'https://modrinth.com/mod/example-mod'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add any context, screenshots, or compatibility notes for this request.
    validations:
      required: false

  - type: dropdown
    id: versions
    attributes:
      label: Game Versions
      description: Which versions of Minecraft should be supported? (You can pick multiple.)
      multiple: true
      options:
        - '26.1'
        - '1.21.11'
        - '1.21.9/1.21.10'
        - '1.21.6-1.21.8'
        - '1.21.5'
        - '1.21.4'
        - '1.21.2/1.21.3'
        - '1.21/1.21.1'
        - '1.20.5/1.20.6'
        - '1.20.3/1.20.4'        
        - '1.20.2'  
        - '1.20/1.20.1'
        - '1.19'
        - '1.18'
        - '1.16'
        - '1.12'
    validations:
      required: true

  - type: dropdown
    id: modloaders
    attributes:
      label: Mod Loaders
      description: Select the applicable mod loader(s) used by the mod.
      multiple: true
      options:
        - Fabric
        - Forge
        - NeoForge
        - Quilt
        - Data Pack
        - Other
    validations:
      required: true
