name: Sync Selected Branches to Codeberg

on:
  push:
    branches:
      - 1.21
      - 1.18
      - 1.16
      - 1.12
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push selected branches to Codeberg
        run: |
          git remote add codeberg https://$CODEBERG_USER:$CODEBERG_TOKEN@codeberg.org/aric3435/Default-Dark-Mode-Expansion.git          
          git push codeberg ${GITHUB_REF_NAME}:${GITHUB_REF_NAME} --force
        env:
          CODEBERG_USER: ${{ secrets.CODEBERG_USER }}
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
